---
- name: Clone repo
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ tomoca_repo_rest }}"
    - "{{ tomoca_repo_site }}"

- name: Put environment file
  become: yes
  template:
    src: .env.j2
    dest: "{{ tomoca_repo_site.dest }}/.env"

- name: Setup rest environment
  become: yes
  shell: "{{ tomoca_repo_rest.dest }}/setup.sh"

- name: Setup site environment
  become: yes
  shell: "{{ tomoca_repo_site.dest }}/scripts/setup.sh"

- name: Chmod repo recursively
  become: yes
  file:
    dest: "{{ item.dest }}"
    owner: root
    mode: 0777
    recurse: yes
  with_items:
    - "{{ tomoca_repo_rest }}"
    - "{{ tomoca_repo_site }}"
