---
- name: Clone repo
  git:
    repo: "{{ tomoca_repo_rest.url }}"
    dest: "{{ tomoca_repo_rest.dest }}"

- name: Setup environment
  become: yes
  shell: "{{ tomoca_repo_rest.dest }}/setup.sh"

- name: Chmod repo recursively
  become: yes
  file:
    dest: "{{ tomoca_repo_rest.dest }}"
    owner: root
    mode: 0777
    recurse: yes
