---
- name: REST service
  become: yes
  template:
    src: rest.service.j2
    dest: /etc/systemd/system/rest.service

- name: enable rest service
  become: yes
  systemd:
    name: rest
    state: started
    enabled: True

- name: website service
  become: yes
  template:
    src: site.service.j2
    dest: /etc/systemd/system/site.service

- name: enable site service
  become: yes
  systemd:
    name: site
    state: started
    enabled: True
