---
- name: REST service
  become: yes
  template:
    src: rest.service.j2
    dest: /etc/systemd/system/rest.service

- name: enable rest service
  systemd:
    name: rest
    state: started
    enabled: True
