---
systemd_rest:
  working_directory: "/home/ubuntu/django-rest-service/django_rest_service"
  exec_start: "/home/ubuntu/django-rest-service/.venv/bin/gunicorn django_rest_service.wsgi --bind=0.0.0.0:8080"

systemd_site:
  working_directory: "/home/ubuntu/corporate-site/project"
  exec_start: "/home/ubuntu/corporate-site/venv/bin/gunicorn project.wsgi --bind=0.0.0.0:8000"
  